version: "3.2"

services:
  database:
    container_name: database_container
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/logs
      - ./mysql/conf:/etc/mysql/conf.d
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  backend:
    container_name: backend_container
    image: node:16.19.0
    command: node /backend.js
    restart: always
    volumes:
      - ../backend/dist/backend.js:/backend.js
    environment:
      NODE_ENV: production
    ports:
      - target: 5000
        published: 5000
    depends_on:
      - database
  refresh:
    container_name: refresh_container
    image: node:16.19.0
    command: node /refresh.js
    restart: always
    volumes:
      - ../backend/dist/refresh.js:/refresh.js
    depends_on:
      - database
  frontend:
    container_name: frontend_container
    image: nginx:1.23.3
    restart: always
    volumes:
      - ../frontend/dist:/app
      - ./nginx_container.conf:/etc/nginx/conf.d/default.conf
    ports:
      - target: 80
        published: 80
    depends_on:
      - backend

