version: '3.2'

services:
  database:
    container_name: database_container
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/logs
      - ./mysql/conf:/etc/mysql/conf.d
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - target: 3306
        published: 3306
  backend:
    container_name: backend_container
    image: node:16.19.0
    command: node /backend.js
    restart: always
    volumes: 
      - ../backend/dist/backend.js:/backend.js
    environment:
      NODE_ENV: production
    ports:
      - target: 5000
        published: 5000
    depends_on:
      - database